[aws]
disabled = true

[docker_context]
disabled = true

[nix_shell]
disabled = true

[package]
disabled = true

# custom module for jj status
[custom.jj]
ignore_timeout = true
description = "The current jj status"
detect_folders = [".jj"]
symbol = "🥋 "
command = '''
jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
  separate(" ",
    change_id.shortest(4),
    bookmarks,
    "|",
    concat(
      if(conflict, "💥"),
      if(divergent, "🚧"),
      if(hidden, "👻"),
      if(immutable, "🔒"),
    ),
    raw_escape_sequence("\x1b[1;32m") ++ if(empty, "(empty)"),
    raw_escape_sequence("\x1b[1;32m") ++ coalesce(
      truncate_end(29, description.first_line(), "…"),
      "(no description set)",
    ) ++ raw_escape_sequence("\x1b[0m"),
  )
'
'''

[git_branch]
disabled = true
[git_commit]
disabled = true
[git_metrics]
disabled = true
[git_state]
disabled = true

# re-enable git as long as we're not in a jj repo
[custom.git_branch]
when = true
command = "jj root >/dev/null 2>&1 || starship module git_branch"
description = "Only show git_branch if we're not in a jj repo"
[custom.git_commit]
when = true
command = "jj root >/dev/null 2>&1 || starship module git_commit"
description = "Only show git_commit if we're not in a jj repo"
[custom.git_metrics]
when = true
command = "jj root >/dev/null 2>&1 || starship module git_metrics"
description = "Only show git_metrics if we're not in a jj repo"
[custom.git_state]
when = true
command = "jj root >/dev/null 2>&1 || starship module git_state"
description = "Only show git_state if we're not in a jj repo"
